# Cloudflare Pages用設定ファイル
# Studio埋め込み対応版

[build]
  publish = "public"

[[redirects]]
  from = "/generator.html"
  to = "/generator.html"
  status = 200
  headers = {X-Frame-Options = "ALLOWALL", "Content-Security-Policy" = "frame-ancestors 'self' *.studio.site *.preview.studio.site"}

[[redirects]]
  from = "/generator.html/*"
  to = "/generator.html"
  status = 200
  headers = {X-Frame-Options = "ALLOWALL", "Content-Security-Policy" = "frame-ancestors 'self' *.studio.site *.preview.studio.site"}

[[redirects]]
  from = "/create"
  to = "/generator.html"
  status = 200
  headers = {X-Frame-Options = "ALLOWALL", "Content-Security-Policy" = "frame-ancestors 'self' *.studio.site *.preview.studio.site"}

[[redirects]]
  from = "/generator"
  to = "/generator.html"
  status = 200
  headers = {X-Frame-Options = "ALLOWALL", "Content-Security-Policy" = "frame-ancestors 'self' *.studio.site *.preview.studio.site"}

[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200

[[redirects]]
  from = "/s/*"
  to = "/s.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
