name = "student-card-share"
main = "index.js"
compatibility_date = "2024-03-14"

[vars]
CLOUDINARY_CLOUD_NAME = ""  # Cloudinaryのcloud_nameを設定
CLOUDINARY_API_KEY = ""     # CloudinaryのAPI Keyを設定

[[assets]]
binding = "ASSETS"
bucket = "../assets/img" 